backend/spec/controllers/spree/admin/images_controller_spec.rb

I think these tests were passing in the past because the image was missing and so it was returning Image not found, but I don't understand why the controller shouldn't be able to delete an image that belongs to any product in the current store.
```ruby
#
context 'cannot destroy image of other product' do
let(:other_product) { create(:product, stores: [store]) }
let(:image) { create(:image, viewable: other_product) }
it { expect(send_request).to redirect_to(spree.admin_product_images_path(product)) }
it do
send_request
expect(flash[:error]).to eq('Image is not found')
end
end
```

Fix For Spec Test Issues - images_controller_spec.rb

---

backend/app/assets/javascripts/spree/backend/cms/page.es6

As the platform API evolved the `cms_section` reposition action was removed, this PR updates the javascript to call update on the position.

Fix for removal of cms_section reposition endpoint from Platform API.

---

app/assets/javascripts/spree/backend/promotions.js

Need to disable select if a promotion action calculator is changed, else the params get dragged through.

Fix switching promotions, preferred_currency select issue.

---

app/views/spree/admin/products/index.html.erb

This locals variable is not used anywhere in the admin/products/index.html.erb template right now since the hooks call no longer exists.

Remove un-used locals variable

---

app/controllers/spree/admin/products_controller.rb
spec/features/admin/products/edit/properties_spec.rb
spec/features/admin/products/products_spec.rb

https://getvendo.atlassian.net/browse/VEN-259

VEN-259 UX: when saving/creating/removing product properties it should redirect back to product properties, not product edit

---

app/controllers/spree/admin/stores_controller.rb
spec/features/admin/configuration/stores_spec.rb

https://getvendo.atlassian.net/browse/VEN-290

VEN-290 When creating a new store, default country should be always the defaylt country of the default store

---

app/assets/stylesheets/spree/backend/components/_sidebar.scss
app/views/spree/admin/shared/_main_menu.html.erb

Transparent menu doesn't work on slide out mode.
Remove excess padding from top of menu.

Fix Main Menu Styling 

---

app/views/spree/admin/shared/_main_menu.html.erb

The mobile menu should have no toppings padding, but the desktop should.
Ideally this should be calculated based off the nav bar height rather than a set bootstrap padding but at the moment there is no set nav bar height.

Only pad menu on large screens.

---

app/views/spree/admin/products/_form.html.erb

There is a UI issue on the product edit details,  if you scroll left to right the main content side scrolls under the menu.
Issue was caused by the new select2 `w-100` class added.

Fix sideways over scroll on edit product details page.

---

app/controllers/spree/admin/products_controller.rb
spec/features/admin/products/products_spec.rb

https://getvendo.atlassian.net/browse/VEN-341
blocked by: https://github.com/spree/spree/pull/11616
State machine after_transition events do not fire on regular `.save` or `.update` and fire only on the events being triggered (for example `product.archive`)

VEN-341 Emit webhooks on Product status change

---

app/controllers/spree/admin/webhooks_subscribers_controller.rb
app/views/spree/admin/webhooks_subscribers/index.html.erb

https://getvendo.atlassian.net/browse/VEN-215 - As a Vendor Owner I can manage Webhook subscribers
When Admin: cannot create a Subscriber for a specific Vendor
When Vendor Owner: can only create Subscriber for his Vendor

VEN-215 Enable setting Vendor for Webhooks Subscribers

---

app/assets/stylesheets/spree/backend/components/_navbar.scss

Use min-height for nav bar so hat it meet the menu top, but can be larger for other contents.

Add a min height for navbar to meet menu.

---

app/helpers/spree/admin/products_helper.rb
spec/helpers/spree/admin/products_helper_spec.rb

We should only show product status, not available on logic here

Drop the pre-order status

---

app/assets/javascripts/spree/backend/address_states.es6

If A customer has in his address details like this B-01/455, Palam Vihar, New Delhi, India 110014. according to this information, the zipcode field gets data as "110014", the city field is get the data as "New Delhi", the country field should get data as "India" and so on.
The Customer details edit page should show the fields according to the corresponding data value of it saved on the database.
Fixes https://github.com/spree/spree/issues/11624

changes add for state field!

---

app/views/spree/admin/shared/_content_header.html.erb

Fix missing scroll right button on horizontal scrolling buttons.
(The `data-nav-x-content` content must tightly wrap its child items, not span 100% width of its parent.)

Fix missing scroll right button off nav-x tabs.

---

app/views/spree/admin/cms_pages/_form.html.erb

Remove col-12 to Stop Overflowing Content.

---

app/views/spree/admin/menu_items/_form.html.erb
app/views/spree/admin/menu_items/_icon_upload_form.html.erb

https://getvendo.atlassian.net/browse/VEN-356
Still trying to figure out some problems with caused in `sortable_tree/_menu` => `main_app.cdn_image_url(item.icon.attachment)`. When I have a Spree::Icon model and attachment in it `cdn_image` does not work. The attachment has no `.blob` or other attributes associated with ActiveStorage, when uploaded through a service

VEN-356 Refactor out MenuItem Icon upload form

---

app/views/spree/admin/adjustments/_adjustments_table.html.erb
app/views/spree/admin/orders/_order_actions.html.erb
config/routes.rb
spec/controllers/spree/admin/orders_controller_spec.rb

The routes for `admin/orders/{orderId}/open_adjustments` , `admin/orders/{orderId}/close_adjustments` , `admin/orders/{orderId}/reset_digitals` currently use GET method, even though they cause state changes on the backend.
This creates a CSRF risk, if an external page loads these paths while the admin is signed in. 
I've changed these routes to use PUT, which is by default protected by CSRF token.

Fix CSRF security issue in adjustments admin panel

---

app/views/spree/admin/shared/_address_form.html.erb

The state field in address forms in the admin panel (e.g. `/admin/users/<id>/addresses` or `/admin/orders/<id>/customer`) is overriden with the first state in alphabetical order.
Clearly visible when refreshing the page - the state is correct at first (in this case Colorado) and after a moment it gets overriden with Alabama:
https://user-images.githubusercontent.com/43988137/169048725-99562561-589b-4db6-a270-4a6e95634758.mov
1. Create an user with a shipping address that has a state (e.g. from the United States)
2. Visit the `/admin/users/<id>/addresses` page
or
1. Create an order with a shipping address that has a state (e.g. from the United States)
2. Visit `/admin/orders/<id>/customer` page
After the page is loaded, the [updateAddressState](https://github.com/spree/spree_backend/blob/ma …

Fix state being overriden in address forms

---

Gemfile

Lock puma version to `< 6.0`, as 6.0 is not compatible with the capybara version we use

Lock puma version for tests

---

app/views/spree/admin/stores/new.html.erb
spec/features/admin/store_selector_spec.rb

The "Stores" page was removed in favor of a dropdown menu, but the /admin/stores/new page still contains a link to it.
I removed it, because clicking on it causes an error which can be confusing.

Remove "Stores" link in "New store" page navigation

---

app/assets/javascripts/spree/backend/admin.js
app/views/spree/admin/option_types/edit.html.erb

Currently the option to add a new Option Value is available in the top right corner of the page, which is quite far away with the content it modifies and gets confusing. I moved the button right below the list of Option Values, to make it more intuitive.
https://user-images.githubusercontent.com/6420475/196033106-81c4d404-fec8-4247-b43b-5bce4a07c250.mov

Improve UX of the Option Types admin panel

---

app/controllers/concerns/spree/admin/translatable.rb
app/views/spree/admin/translations/_form.html.erb
app/views/spree/admin/translations/_translations_unavailable.html.erb
spec/features/admin/products/edit/translations_spec.rb

This PR contains a fix that ensures that we always generate a slug correctly (triggering @object.save while inside I18n.with_locale).
I've also added some specs that edit the translations via the admin panel UI.

Always trigger generating slugs when saving translations

---

app/controllers/concerns/spree/admin/product_concern.rb
app/controllers/spree/admin/base_controller.rb

By introducing Mobility, we moved the translations to a separate table. If we don't preload translations explicitly, displaying them on the UI will trigger n + 1 queries in places where we display a list of translatable records.
I started profiling the admin panel and optimizing performance in some places that I think make sense:
- Stores - this is a list that renders in the navbar, in every view in the admin panel. For setups with a larger amount of stores, the performance issue will be issue on every single page
- Products - the list of products already triggers some n+1 queries, which should be optimized. Displaying product name in the product list had a visible impact on the performance.
I was also trying to add a similar optimization in the `TaxonomiesController#edit` (displays a …

Optimize performance of loading translations

---

app/controllers/spree/admin/data_feeds_controller.rb
app/views/spree/admin/data_feeds/_form.html.erb
app/views/spree/admin/data_feeds/edit.html.erb
app/views/spree/admin/data_feeds/index.html.erb
app/views/spree/admin/data_feeds/new.html.erb
app/views/spree/admin/shared/sub_menu/_integrations.html.erb
config/locales/en.yml
config/routes.rb

This PR relies on https://github.com/spree/spree/pull/11877
In this PR, I've added a separate admin page for managing data feeds (available via "Integrations" menu on the left hand side). 
TBD: Make selecting a provider more intuitive

Add admin panel for managing data feeds

---

app/views/spree/admin/dashboard/_getting_started.html.erb
config/locales/en.yml

Changed the message from "add products manually through the API or import from a CSV file" to "You can add products manually or import them via the API" with a link to the documentation. This branch should be also merged to 4-6-stable and 4-5-stable. It also has some Spanish translations in spree_i18n, so it's worth updating it together.

Remove "or import from CSV" from the label in the admin panel - SP-72

---

app/controllers/spree/admin/oauth_applications_controller.rb
app/views/spree/admin/oauth_applications/index.html.erb
config/locales/en.yml

Notice with link to documentation added. Not sure if using flash notice is the best way to do it, so please review it. Also, the message can be updated. I'm attaching a photo to show you how it looks like for now.

Link to documentation added in Oauth applications list in admin panel SP-68

---

app/controllers/concerns/spree/admin/translatable.rb

Fix to situation, where it was not possible to add a translation of taxonomy, when the language of a store was not English. 
The solution includes changing the way the translation is saved.

Adding translation to taxonomy fix

---

.circleci/config.yml
Gemfile

This PR unlocks some dependencies used in the CircleCI test pipeline, that don't need to be locked anymore

Bump test dependencies

---

app/views/spree/admin/cms_sections/types/_image_gallery.html.erb
app/views/spree/admin/cms_sections/types/_side_by_side_images.html.erb

Some layouts depended on the `rails_5?` method provided by one of the helpers in Spree core. The method was removed, as we no longer support Rails 5, which broke some templates. This PR fixes that.

Fix layout depending on rails_5? helper

---

config/locales/en.yml

There's a `utilities.preview` label in the codebase, that allows to inject a custom name parameter to it. This is only used for products, and looking at how we use it, it doesn't even make that much sense to specify the target of the preview - it's obvious from the context

Update preview label

---

app/views/spree/admin/shared/_order_tabs.html.erb
app/views/spree/admin/shared/_product_tabs.html.erb
app/views/spree/admin/shared/_tabs.html.erb
app/views/spree/admin/users/_tabs.html.erb

This PR adds a spree/admin/shared/tabs partial, which unifies the logic for rendering tabs to a single place. 
This way extensions can also render tabs for their custom entities, without much hassle.

Add generic tabs partial

---

spec/spec_helper.rb

Follow-up to https://github.com/spree/spree/pull/11964

Remove Spree::Config[:default_country_id] usages

---

app/views/spree/admin/shared/_version.html.erb
lib/spree/backend/configuration.rb
lib/spree/backend/engine.rb
lib/spree/backend/runtime_configuration.rb
lib/spree_backend.rb
spec/features/admin/homepage_spec.rb
spec/lib/spree/core_spec.rb

Some preferences like `admin_path` cannot be changed dynamically in a running application, therefore it doesn't make sense to persist them in the database. 
This PR follows-up on https://github.com/spree/spree/pull/11965/files , which introduced a `RuntimeConfiguration` class, and moves `admin_path` (that's used when defining routes upon application boot) and `admin_show_version` (which I think doesn't really make sense to be dynamically configurable, but I'm open to discuss that).

Use runtime configuration for admin_path

---

app/views/spree/admin/webhooks_subscribers/index.html.erb

The Webhook secret keys are displayed alongside different data in admin panel.
Secret keys are hidden until the user toggles their visibility. The UI and the logic of the toggle button is the same as [here](https://spree-staging-4-7.upsidelab.net/admin/oauth_applications).

Display webhook secret key in admin panel

---

app/controllers/spree/admin/products_controller.rb
app/views/spree/admin/prototypes/show.html.erb
spec/features/admin/products/products_spec.rb

Due to Rails bug with sending nested parameters via post parameters there was an issue with missing variants when adding a new product with selected prototype. This PR changes approach to sending the data, fixing the issue.

Fix an issue with missing variants when adding a new product with a prototype

---

app/assets/javascripts/spree/backend/global/tinymce.es6

According to TinyMCE docs, in order to have a lists feature in TinyMCE, one needs to add `lists` plugin to `lists` array. It's not configured this way in spree_backend therefore list buttons specified in `toolbar` are not being respected and end user is not being able to add/edit lists.
https://www.tiny.cloud/docs/plugins/opensource/lists/

Fix lists plugin configuration for TinyMCE

---

app/views/spree/admin/payment_methods/_form.html.erb
config/locales/en.yml

Allows user to define a custom partial view containing instructions for Payment Method configuration. 
1. Create partial view file in `/spree_backend/app/views/spree/admin/payment_methods/configuration_guides/`- create the `configuration_guides` folder if it doesn't exist.
2. The name of the file has to follow the formula: `_name.html.erb`.
3. Define a method `payment_configuration_guide` in chosen Payment Method class declaration. It should return the name of partial file.
1. Create partial `_bogus_partial.html.erb` in said directory. Contents of example partial file:
```
hi, I'm working!
```
2. Find the Spree::Gateway::Bogus class declaration. For this example the path is: `/spree/core/app/models/spree/gateway/bogus.rb`. Add following method to class declaration:
```ruby
def …
```

Allow PaymentMethod to register a custom partial view to display above "Payment Provider Settings"

---

app/views/spree/admin/promotions/index.html.erb

Fix Promotions#index view when a promotion has `expires_at` set.
https://upsidelab.atlassian.net/browse/SP-178
Promotion#index view breaks due to an `ArgumentError`:
`(wrong number of arguments (given 1, expected 0) (ArgumentError))`
Deletion of unnecessary conversion to String (along with faulty argument passing).

Fix Promotions#index view when a promotion has expires_at set

---

app/controllers/spree/admin/adjustments_controller.rb

adjustments missing callback action bug fix

---

config/initializers/assets.rb

This is already set in spree core - https://github.com/spree/spree/commit/9b0d993697faa435023f9b2c7ffa478262cec8d5

Remove `yaml_column_permitted_classes`
