app/assets/javascripts/spree/backend/cms/page.es6, app/assets/javascripts/spree/backend/menus/menu.es6
- Menu Items
- CMS Page Visibility toggle
- CMS Section Reordering 
Remove forcing to integer for IDs on those items
=> Use Spree Fetch Utility for API requests

app/assets/javascripts/spree/backend.js, app/assets/javascripts/spree/backend/shipments.js, app/views/spree/admin/variants/_split.js.erb, spec/features/admin/orders/order_details_spec.rb, spec/spec_helper.rb
requires https://github.com/spree/spree/pull/11494
=> Use Platform API for handling Shipments

app/controllers/spree/admin/digitals_controller.rb, app/views/spree/admin/digitals/_form.html.erb, app/views/spree/admin/stores/_form.html.erb, app/views/spree/admin/variants/index.html.erb, config/locales/en.yml, config/routes.rb, spec/controllers/spree/admin/digitals_controller_spec.rb
- Fix Variants column spacing.
- Add missing Store settings for digital downloads.
- Fix missing template.
=> Fix Digital Download Bugs

app/views/spree/admin/cms_sections/types/_hero_image.html.erb, app/views/spree/admin/cms_sections/types/_image_gallery.html.erb, app/views/spree/admin/cms_sections/types/_side_by_side_images.html.erb, app/views/spree/admin/stores/_form.html.erb
This reverts commit 2c4fd7d0228cd6cf62c4e2e4bf67eb80db008133.
=> Revert "Fixed syntax for RubyVips"

app/views/spree/admin/cms_sections/types/_hero_image.html.erb, app/views/spree/admin/cms_sections/types/_image_gallery.html.erb, app/views/spree/admin/cms_sections/types/_side_by_side_images.html.erb, app/views/spree/admin/stores/_form.html.erb
Reverts spree/spree_backend#67
=> Fixed syntax for RubyVips

app/views/spree/admin/customer_returns/new.html.erb, app/views/spree/admin/digitals/_form.html.erb, app/views/spree/admin/oauth_applications/_form.html.erb, app/views/spree/admin/option_types/_form.html.erb, app/views/spree/admin/option_types/edit.html.erb, app/views/spree/admin/products/new.html.erb, app/views/spree/admin/properties/_form.html.erb, app/views/spree/admin/prototypes/_form.html.erb, app/views/spree/admin/return_authorizations/_form.html.erb, app/views/spree/admin/roles/_form.html.erb, app/views/spree/admin/shared/named_types/_form.html.erb, app/views/spree/admin/stock_locations/_form.html.erb, app/views/spree/admin/store_credit_categories/_form.html.erb, app/views/spree/admin/taxonomies/_form.html.erb, app/views/spree/admin/webhooks_subscribers/_form.html.erb, spec/features/admin/configuration/stock_locations_spec.rb
https://getvendo.atlassian.net/browse/VEN-212
=> VEN-212 Use required_span_tag for red asterisk on required fields

app/controllers/spree/admin/return_index_controller.rb, spec/controllers/spree/admin/return_index_controller_spec.rb
blocked by https://github.com/spree/spree/pull/11575
=> VEN-218 Show Return Authorizations from current store only

app/views/spree/admin/shared/_main_menu.html.erb, app/views/spree/admin/shared/sub_menu/_configuration.html.erb, app/views/spree/admin/shared/sub_menu/_integrations.html.erb
https://getvendo.atlassian.net/browse/VEN-224
=> VEN-224 Admin: Move Payment methods from Configurations to Integrations

app/views/spree/admin/stores/form/_internationalization.html.erb, spec/features/admin/configuration/stores_spec.rb
https://getvendo.atlassian.net/browse/VEN-210
=> VEN-210 Do not set checkout zone for new store

app/controllers/spree/admin/option_types_controller.rb, spec/features/admin/option_types/edit_option_type_spec.rb
https://getvendo.atlassian.net/browse/VEN-226 - Admin UX: after updating option type it should redirect me back to edit option type screen
=> VEN-226 Redirect to edit page after updating option type

Gemfile, app/views/spree/admin/shared/_product_tabs.html.erb, spec/features/admin/orders/order_details_spec.rb, spec/features/admin/orders/shipments_spec.rb, spec/features/admin/products/stock_management_spec.rb
Fixes for https://github.com/spree/spree/commit/c1aebea02b2be8fb50b7a168dbb7708fd7e44f82
=> Disable stock location propagation

app/assets/stylesheets/spree/backend/components/_badges.scss, app/views/spree/admin/orders/_search.html.erb, app/views/spree/admin/orders/index.html.erb, app/views/spree/admin/shared/_main_menu.html.erb, app/views/spree/admin/shared/_table_filter.html.erb, app/views/spree/admin/shared/sub_menu/_orders.html.erb, config/locales/en.yml, spec/features/admin/homepage_spec.rb, spec/features/admin/locale_spec.rb, spec/features/admin/menus/index_menu_spec.rb, spec/features/admin/orders/listing_spec.rb, spec/features/admin/orders/risk_analysis_spec.rb, spec/features/admin/products/products_spec.rb, spec/features/admin/products/properties_spec.rb, spec/features/admin/promotions/adjustments_spec.rb, spec/features/admin/returns/customer_returns_spec.rb, spec/features/admin/returns/return_authorizations_spec.rb, spec/features/admin/users_spec.rb
3 different lists - All (placed) orders, Draft orders, Abandoned checkouts
TODO:
=> VEN-297 Improved Orders list

app/views/spree/admin/products/_filters.html.erb, app/views/spree/admin/products/index.html.erb
https://getvendo.atlassian.net/browse/VEN-311 - this PR is so that you don't have to override the entire products/index view if you want to change filters
=> VEN-311 Refactor products index filters to partial

app/views/spree/admin/webhooks_subscribers/_form.html.erb
https://getvendo.atlassian.net/browse/VEN-346
=> VEN-346 Emit webhooks when Vendor is created, updated, vendor state changes

app/javascript/spree/dashboard/index.js, app/javascript/spree/dashboard/utilities/request_utility.js, lib/generators/spree/backend/install/templates/app/javascript/spree-dashboard.js, package.json, yarn.lock
Parent apps have turbo pre-installed by default and this lead to loading turbo twice
=> Drop @hotwired/turbo dependency

app/views/spree/admin/stores/form/_layout.html.erb, spec/controllers/spree/admin/stores_controller_spec.rb, spec/features/admin/configuration/stores_spec.rb
https://getvendo.atlassian.net/browse/VEN-354
=> VEN-354 Upload store images as new models

app/controllers/spree/admin/payment_methods_controller.rb
https://getvendo.atlassian.net/browse/VEN-367
=> VEN-367 Refactor out payment methods after create location

app/controllers/spree/admin/products_controller.rb, app/views/spree/admin/products/_form.html.erb, spec/controllers/spree/admin/products_controller_spec.rb
https://getvendo.atlassian.net/browse/VEN-444
=> VEN-444 Permit only changing Product status to active

app/views/spree/admin/cms_sections/_image_upload_form.html.erb, app/views/spree/admin/cms_sections/types/_hero_image.html.erb, app/views/spree/admin/cms_sections/types/_image_gallery.html.erb, app/views/spree/admin/cms_sections/types/_side_by_side_images.html.erb
https://getvendo.atlassian.net/browse/VEN-355
blocked by https://github.com/spree/spree/pull/11627
=> VEN-355 Make CmsSection forms to work with new CmsSectionImage models

app/helpers/spree/admin/base_helper.rb, app/views/spree/admin/cms_sections/_form.html.erb
This should be merged before https://github.com/spree/spree_backend/pull/173
=> Fix getting dropdown values out of cms sections

app/controllers/spree/admin/oauth_applications_controller.rb, app/controllers/spree/admin/resource_controller.rb, spec/features/admin/cms_sections/side_by_side_images_spec.rb
This should be probably merged after https://github.com/spree/spree_backend/pull/173, so it would be automatically tested.
=> Fix Separate turbo

spec/controllers/spree/admin/base_controller_spec.rb, spec/features/admin/orders/cancelling_and_resuming_spec.rb
Adds selected locale to attributes of mocked user.
=> add selected locale to user mocks

app/views/spree/admin/dashboard/_getting_started.html.erb, config/locales/en.yml
According to what was discussed with @rafalcymerys , I copy the same PR against 4-5-stable
=> feat: add translations to getting started section

Gemfile, spec/features/admin/products/products_spec.rb
- Bump capybara and webdrivers versions
- Fix feature spec failing due to changes in Chrome
- Temporarily disable a failing spec that needs further investigation
=> Fix feature spec issues

Gemfile, spec/features/admin/products/products_spec.rb
=> Fix feature spec issues [Spree 4.6]

app/views/spree/admin/oauth_applications/index.html.erb, config/locales/en.yml
Porting https://github.com/spree/spree_backend/pull/267 and #266 to Spree 4.6
=> Link documentation for oauth applications

app/views/spree/admin/dashboard/_getting_started.html.erb, config/locales/en.yml
=> Remove import from csv from label (Spree 4.6)

app/helpers/spree/admin/navigation_helper.rb
Follow-up to https://github.com/spree/spree/pull/11952/files
=> Use dedicated deprecator

app/assets/javascripts/spree/backend/global/tinymce.es6
Porting https://github.com/spree/spree_backend/pull/297 to upstream Spree
=> Add lists plugin for TinyMCE

app/views/spree/admin/webhooks_subscribers/index.html.erb
Ports https://github.com/spree/spree_backend/pull/293 to Spree 4.6
=> Display webhook secret key in admin panel (Spree 4.6)

app/views/spree/admin/webhooks_subscribers/index.html.erb
Ports https://github.com/spree/spree_backend/pull/293 to Spree 4.7
=>  Display webhook secret key in admin panel (Spree 4.7)

app/controllers/concerns/spree/admin/translatable.rb, spec/features/admin/products/edit/translations_spec.rb
=> Fix updating translations
